In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
cnn_results = pd.read_csv("../results/task1_cnn_results.csv")
lstm_results = pd.read_csv("../results/task1_lstm_results.csv")

comparison = pd.concat(
    [cnn_results, lstm_results],
    ignore_index=True
)

comparison["RMSE"] = comparison["RMSE"].round(4)
comparison["MAE"] = comparison["MAE"].round(4)

comparison

                                Task Model    RMSE     MAE
0     Task 1.1 - Next-day prediction   CNN  0.0254  0.0173
1      Task 1.2 - 7th day prediction   CNN  0.1604  0.1276
2  Task 1.3 - Next 7 days prediction   CNN  0.0645  0.0442
3      Task 1.2 - 7th day prediction  LSTM  0.1128  0.0738
4  Task 1.3 - Next 7 days prediction  LSTM  0.1733  0.1160

In [5]:
best_models = comparison.loc[
    comparison.groupby("Task")["RMSE"].idxmin()
].reset_index(drop=True)

best_models

                                Task Model    RMSE     MAE
0     Task 1.1 - Next-day prediction   CNN  0.0254  0.0173
1      Task 1.2 - 7th day prediction  LSTM  0.1128  0.0738
2  Task 1.3 - Next 7 days prediction   CNN  0.0645  0.0442

In [6]:
comparison.to_csv("../results/task1_model_comparison.csv", index=False)
best_models.to_csv("../results/task1_best_models.csv", index=False)